# Assignment For Numpy¶

# Difficulty Level Beginner

#### Import the numpy package under the name np

In [217]:
import numpy as np

#### Create a null vector of size 10

In [218]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a vector with values ranging from 10 to 49

In [219]:
x=np.arange(10,49)

In [220]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### Find the shape of previous array in question 3

In [221]:
x.shape

(39,)

#### Print the type of the previous array in question 3

In [222]:
x.dtype

dtype('int32')

#### Print the numpy version and the configuration

In [223]:
print(np.__version__)

1.18.1


In [224]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/USER/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:

#### Print the dimension of the array in question 3

In [225]:
x.ndim

1

#### Create a boolean array with all the True values

In [226]:
x=np.array([6,7,8,9,10])

In [227]:
y=x>5

In [228]:
y

array([ True,  True,  True,  True,  True])

#### Create a two dimensional array

In [229]:
arr2D=np.array([[1,2,3],[4,5,6]])

In [230]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

#### Create a three dimensional array

In [231]:
arr3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [232]:
arr3D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# Difficulty Level Easy

#### Reverse a vector (first element becomes last)

In [233]:
arrRO=np.arange(1,10)

In [234]:
arrRO

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [235]:
arrRO = arrRO[::-1]

In [236]:
arrRO

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### Create a null vector of size 10 but the fifth value which is 1

In [237]:
Nvs10 = np.zeros(10)

In [238]:
Nvs10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [239]:
Nvs10[4]=1

In [240]:
Nvs10

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Create a 3x3 identity matrix

In [241]:
IM=np.identity(3)

In [242]:
IM

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### arr = np.array([1, 2, 3, 4, 5])

#### Convert the data type of the given array from int to float# 

In [243]:
arr=np.array([1,2,3,4,5])

In [244]:
arr

array([1, 2, 3, 4, 5])

In [245]:
arr.astype(float)

array([1., 2., 3., 4., 5.])

#### Multiply arr1 with arr2

In [246]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  

In [247]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

In [248]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

##### Mehthod 2

In [249]:
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

#### Make an array by comparing both the arrays provided above

In [250]:
np.array_equal(arr1,arr2)

False

#### Extract all odd numbers from arr with values(0-9)

In [251]:
x=np.arange(9)

In [252]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [253]:
l=x[x%2==1]

In [254]:
l

array([1, 3, 5, 7])

#### Replace all odd numbers to -1 from previous array

In [255]:
l[l==l]=-1

In [256]:
l

array([-1, -1, -1, -1])

#### Create a 2d array with 1 on the border and 0 inside

In [257]:
x=np.ones((5,5))

In [258]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [259]:
x[1:-1,1:-1]=0

In [260]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Difficulty Level Medium

#### Replace the value 5 to 12

In [261]:
arr2d  = np.array([[1, 2, 3],[4, 5,6],[7, 8, 9]])

In [262]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [263]:
arr2d[arr2d==5]=12

In [264]:
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

#### Convert all the values of 1st array to 64

In [265]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [266]:
arr3d [0]=64

In [267]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [268]:
arr2ddD=np.array(range(0,9)).reshape(3,3)

In [269]:
arr2ddD[0]

array([0, 1, 2])

#### Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [270]:
arr2ddD [::,2]


array([2, 5, 8])

#### Create a 10x10 array with random values and find the minimum and maximum values

In [271]:
z = np.random.randn(10,10)

In [272]:
z

array([[ 1.01398665, -1.47593994, -0.0597668 ,  1.13617453,  0.13667479,
         0.22391195, -0.2379867 ,  0.63217731, -1.96040646,  1.23246536],
       [ 1.56684987,  0.30783209,  0.85337082, -0.53696174,  0.99194816,
         2.16366442, -0.25847639,  1.16994519,  0.36435537, -0.20971604],
       [ 0.32996157, -0.94764484,  0.33268941, -0.63090264,  0.73306679,
         1.01029236,  1.24587945, -0.17266475, -0.22335174, -0.57790541],
       [ 1.64216296,  0.07112314,  0.58820176,  2.16645796, -0.7894037 ,
        -0.40131019,  1.64859849,  0.53523114,  0.36078902,  1.26423558],
       [ 0.48107629,  1.01481406,  0.820234  ,  0.82264579,  0.0290324 ,
         0.63934943,  0.56635192, -0.21242871,  1.98620664,  0.02100261],
       [-0.3917774 ,  0.48798817,  0.14587365, -0.53144258,  0.47114044,
         0.38345079, -0.30987515,  0.7377138 ,  0.23499293,  0.19165226],
       [-1.04182361,  0.1982625 ,  1.17502465,  0.66177591, -0.12797619,
         0.59366894,  0.61546149,  1.15249654

In [273]:
np.amax(z)

2.1664579575172214

In [274]:
np.amin(z)

-2.2597911914477393

#### Find the common items between a and b

In [275]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

In [276]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [277]:
np.intersect1d(a,b)

array([2, 4])

#### Find the positions where elements of a and b match

In [278]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

In [279]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [280]:
res= np.where(a == b)

In [281]:
res

(array([1, 3, 5, 7], dtype=int64),)

#### Find all the values from array data where the values from array names are not equal to Will

In [282]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [283]:
data = np.random.randn(7, 4)

In [284]:
np.where("Will" != "Joe")

(array([0], dtype=int64),)

#### Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15


In [285]:
arr2d = np.array(range(1,16)).reshape(5,3)

In [286]:
arr2d.astype('float32')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float32)

#### Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [301]:
arr10 = np.array(range(10))

In [302]:
np.square(arr10)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

#### Find the unique names and sort them out!

In [211]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [212]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

#### Find the dot product of the above two matrix

In [329]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 

In [330]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [331]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

#### Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [287]:
myArr = np.array(range(1,17)).reshape(2,2,4)

In [289]:
myArr.astype('float32')

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float32)